name: auto_share

on:
  workflow_dispatch:
  schedule:
     - cron: '13 9,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        run: |
          git clone -b qx https://github.com/MachelleZhang/QuantumultX.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
      - name: '运行'
        run: |
          cd ~/js   
          node js/youthshare.js
